/* ----------------------------------------------------------------------------
 *		 
 *        mboot for Lophilo embedded system
 *		
 * ----------------------------------------------------------------------------
 */

#include <string.h>

#include "types.h"
#include "trace.h"
#include "option.h"
#include "mboot.h"
#include "media.h"
#include "sha204.h"

#include "sfr.h"
#include "board.h"
#include "system.h"
#include "twi.h"
#include "fpga.h"
#include "leds.h"
#include "uart.h"
#include "emac.h"
#include "rtc.h"

#include "init.h"

static void mbootBanner(void);

int main()
{
	BTNDIS_P();
	Init_LEDS();
	Init_TIMER();
	Init_FPGA();
	Init_UART();
	Init_TWI(100000);
	
	mbootBanner();
	
	Init_RTC();
	Init_Media();
	Init_SHA204();
	Init_EMAC();
	SYS_UNRESET();
	
	mboot();

	while(1);
}

static void mbootBanner(void)
{
	ShellAllClear();
	
	SHELL_INF("        __                      __"); 
	SHELL_INF("       /\\ \\                    /\\ \\__"); 
	SHELL_INF("___ ___\\ \\ \\____    ___     ___\\ \\ ,_\\"); 
	SHELL_INF(" __` __`\\ \\ '__`\\  / __`\\  / __`\\ \\ \\/"); 
	SHELL_INF(" \\/\\ \\/\\ \\ \\ \\_\\ \\/\\ \\_\\ \\/\\ \\_\\ \\ \\ \\_"); 
	SHELL_INF("\\_\\ \\_\\ \\_\\ \\_,__/\\ \\____/\\ \\____/\\ \\__\\"); 
	SHELL_INF("/_/\\/_/\\/_/\\/___/  \\/___/  \\/___/  \\/__/"); 
	
	// Above banner is generated by: http://www.network-science.de/ascii/
	// HTML-Frontend (c) 1996-2012 by Jorg Seyfferth
	
	SHELL_EMPTY();
	SHELL_INF("Lophilo-mboot ver%s-(%s)", MBOOT_VER, __DATE__);
	SHELL_INF("By Shyu Lee and Ricky Ng-Adam");
	SHELL_BNNER();
	SHELL_EMPTY();
}
